/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biodatap2;

/**
 *
 * @author D-2
 */
public class BiodataP22 extends javax.swing.JFrame {

    /**
     * Creates new form BiodataP22
     */
    String nama,jk,alamat,pendidikan,hbsepeda,hbrenang,hbbaca,hbmendaki;
;
    public BiodataP22() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupJK = new javax.swing.ButtonGroup();
        txthobi = new javax.swing.JLabel();
        prsbersepeda = new java.awt.Checkbox();
        prsberenang = new java.awt.Checkbox();
        prsmembaca = new java.awt.Checkbox();
        prsmendaki = new java.awt.Checkbox();
        txtjeniskelamin = new javax.swing.JLabel();
        prslaki = new javax.swing.JRadioButton();
        prsperempuan = new javax.swing.JRadioButton();
        txtalamat = new javax.swing.JLabel();
        txtjenjangpendidikan = new javax.swing.JLabel();
        txtbiodata = new javax.swing.JLabel();
        btnproses = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        prsjenjangpendidikan = new javax.swing.JComboBox<>();
        prsalamat = new javax.swing.JScrollPane();
        prsalamatt = new javax.swing.JTextArea();
        txtnama = new javax.swing.JLabel();
        prsnama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txthobi.setText("Hobi");

        prsbersepeda.setLabel("Bersepeda");

        prsberenang.setLabel("Berenang");

        prsmembaca.setLabel("Membaca");

        prsmendaki.setLabel("Mendaki");

        txtjeniskelamin.setText("Jenis Kelamin");

        groupJK.add(prslaki);
        prslaki.setSelected(true);
        prslaki.setText("Laki-Laki");

        groupJK.add(prsperempuan);
        prsperempuan.setText("Perempuan");

        txtalamat.setText("Alamat");

        txtjenjangpendidikan.setText("Jenjang Pendidikan");

        txtbiodata.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtbiodata.setText("BIODATA");

        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");

        prsjenjangpendidikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Sekolah", "SD", "SMP", "SMA/SMK", "D1", "D2", "D3", "S1", "S2" }));

        prsalamatt.setColumns(20);
        prsalamatt.setRows(5);
        prsalamat.setViewportView(prsalamatt);

        txtnama.setText("Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnama)
                    .addComponent(txtalamat)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtjenjangpendidikan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prsjenjangpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthobi)
                            .addComponent(txtjeniskelamin))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prslaki)
                                .addGap(18, 18, 18)
                                .addComponent(prsperempuan))
                            .addComponent(prsmendaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prsberenang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prsbersepeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(prsmembaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnhapus)
                                        .addGap(34, 34, 34)))
                                .addComponent(btnkeluar))
                            .addComponent(prsalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prsnama, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnproses))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(txtbiodata)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtbiodata)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama)
                    .addComponent(prsnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjeniskelamin)
                    .addComponent(prslaki)
                    .addComponent(prsperempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtalamat)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(prsalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjenjangpendidikan)
                    .addComponent(prsjenjangpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prsbersepeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthobi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prsberenang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prsmembaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prsmendaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnproses)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        nama = prsnama.getText();
        alamat = prsalamatt.getText();
        pendidikan = prsjenjangpendidikan.getSelectedItem().toString();
        if(prslaki.isSelected()){
            jk = "Laki-Laki";
        }  else{
            jk = "Perempuan";  
            
            
        if(prsbersepeda.isSelected()){
            hbsepeda = "Bersepeda";
        }else{
            hbsepeda = "";
        }
        if(prsberenang.isSelected()){
            hbrenang = "Bersepeda";
        }else{
            hbrenang = "";
        }
        if(prsmembaca.isSelected()){
            hbbaca = "Bersepeda";
        }else{
            hbbaca = "";
        }
        if(prsmendaki.isSelected()){
            hbmendaki = "Bersepeda";
        }else{
            hbmendaki = "";           
    }//GEN-LAST:event_btnprosesActionPerformed
        
                
        
    


    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        prsnama.setText("");
        prsalamatt.setText("");
        groupJK.clearSelection();
        prsjenjangpendidikan.setSelectedItem(null);
        prsbersepeda.setSelected(false);
        prsberenang.setSelected(false);
        prsmembaca.setSelected(false);
        prsmendaki.setSelected(false);
        
        
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataP22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataP22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataP22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataP22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataP22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnproses;
    private javax.swing.ButtonGroup groupJK;
    private javax.swing.JScrollPane prsalamat;
    private javax.swing.JTextArea prsalamatt;
    private java.awt.Checkbox prsberenang;
    private java.awt.Checkbox prsbersepeda;
    private javax.swing.JComboBox<String> prsjenjangpendidikan;
    private javax.swing.JRadioButton prslaki;
    private java.awt.Checkbox prsmembaca;
    private java.awt.Checkbox prsmendaki;
    private javax.swing.JTextField prsnama;
    private javax.swing.JRadioButton prsperempuan;
    private javax.swing.JLabel txtalamat;
    private javax.swing.JLabel txtbiodata;
    private javax.swing.JLabel txthobi;
    private javax.swing.JLabel txtjeniskelamin;
    private javax.swing.JLabel txtjenjangpendidikan;
    private javax.swing.JLabel txtnama;
    // End of variables declaration//GEN-END:variables
}
